/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package net.nanai10a.discord.bot.potato;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
